theme: minima
plugins:
  - jekyll-feed
title: My Website 
author: Sai Sruti Sitharaman
email: saisruti1229@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website about me! 
baseurl: "/Sruti" 
url: "https://saisruti1229.github.io"

# social links
instagram_username: sruti2912 # DO NOT include the @ character, or else the build will fail!
github_username: saisruti1229 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
